USE [master]
GO

/****** Object:  Database [nalco_materials]    Script Date: 20-06-2017 09:27:09 AM ******/
CREATE DATABASE [nalco_materials]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'nalco_materials', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\nalco_materials.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'nalco_materials_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\nalco_materials_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [nalco_materials] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [nalco_materials].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [nalco_materials] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [nalco_materials] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [nalco_materials] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [nalco_materials] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [nalco_materials] SET ARITHABORT OFF 
GO

ALTER DATABASE [nalco_materials] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [nalco_materials] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [nalco_materials] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [nalco_materials] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [nalco_materials] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [nalco_materials] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [nalco_materials] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [nalco_materials] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [nalco_materials] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [nalco_materials] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [nalco_materials] SET  DISABLE_BROKER 
GO

ALTER DATABASE [nalco_materials] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [nalco_materials] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [nalco_materials] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [nalco_materials] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [nalco_materials] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [nalco_materials] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [nalco_materials] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [nalco_materials] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [nalco_materials] SET  MULTI_USER 
GO

ALTER DATABASE [nalco_materials] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [nalco_materials] SET DB_CHAINING OFF 
GO

ALTER DATABASE [nalco_materials] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [nalco_materials] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [nalco_materials] SET  READ_WRITE 
GO

